# Generated by Django 2.2.7 on 2020-04-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='file_remarks',
            field=models.CharField(default=151, max_length=128, verbose_name='备注'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='file_user',
            field=models.CharField(default=1, max_length=128, verbose_name='上传者'),
            preserve_default=False,
        ),
    ]
